### Arithmetic operators

In [ ]:
# NumPy arithmetic =
# “Apply operation to every element automatically”

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a%b)
print(a//b)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[0 0 0]
[1 2 3]


In [9]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a%b)
print(a//b)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 5 12]
 [21 32]]
[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


### Comparison operators

In [ ]:
# Comparison operators are used to compare values in arrays and return True / False.
# 👉 In NumPy, they work element-wise (on each element separately)


# Comparison operators in NumPy:
# Work element-wise
# Return boolean arrays
# Used for filtering and conditions

In [20]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

a>1
a==1
a[a > 2]  ## boolean indexing
a[(a > 1) & (a < 4)]  ## Combining Conditions


[1 2 3 4]


array([2, 3])

### Logical operators

In [21]:
# In NumPy:
        # NEVER use and, or, not
        # ALWAYS use &, |, ~


# Logical operators are used to combine conditions (True/False arrays).
# 👉 They are mostly used in boolean indexing (filtering data)

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])

a[(a > 1) & (a < 4)]

a[(a < 2) | (a > 3)]

a[~(a > 2)]


# Always Use Brackets
# # ✅ Correct
# (a > 1) & (a < 4)
# # ❌ Wrong
# a > 1 & a < 4

### Assignment operators

In [ ]:
# Assignment operators are used to update values in an array.
# 👉 They work element-wise (just like other NumPy operations)

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
a = np.array([10, 20, 30])   ## Basic Assignment (=)
print(a)

In [22]:
a = np.array([1, 2, 3])
a += 5
print(a)

[6 7 8]


In [24]:
a = np.array([1, 2, 3])
a *= 3
print(a)

a = np.array([5, 6, 7])
a //= 2
print(a)

[3 6 9]
[2 3 3]


### Special NumPy Operations (Functions)

In [ ]:
# These are built-in NumPy functions that make calculations faster and easier than normal Python.
# 👉 Think of them as ready-made powerful tools

In [ ]:
import numpy as np

a = np.array([1, 4, 9])
print(a)

np.sqrt(a)
np.exp(a)
np.log(a)

[1 4 9]


In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.add(a, b)        # same as a + b
np.subtract(a, b)   # same as a - b
np.multiply(a, b)   # same as a * b
np.divide(a, b)     # same as a / b

array([0.25, 0.4 , 0.5 ])

In [29]:
a = np.array([1, 2, 3, 4])

np.mean(a)
np.std(a)
np.max(a)
np.min(a)

np.int64(1)

### Matrix Operators

In [ ]:
# Matrix operations are used when working with 2D arrays (rows × columns).

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A + B
A - B
A * B  ## Element-wise Multiplication, Not real matrix multiplication!


array([[ 5, 12],
       [21, 32]])

In [35]:
A @ B   ## Matrix Multiplication

# For matrix multiplication: (columns of A) = (rows of B)

array([[19, 22],
       [43, 50]])

In [ ]:
print(np.dot(A,B))   ## Same as A @ B

[[19 22]
 [43 50]]
