In [77]:
import numpy as np

In [78]:
scalar = np.array(1)                        ## scalar
print(scalar)
print(type(scalar))

# print(np.array(1,2))

# 0-dimensional NumPy array, also called a scalar array.
# A scalar means a single number (not a list or matrix).

1
<class 'numpy.ndarray'>


In [79]:
arr1 = np.array([1,2,3,4,5])                  ## vector         1d array
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [80]:
arr2 = np.array([[1,2,3],[4,5,6]])             ## matrices     2d array
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [81]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])       ## tensor   3d array
print(arr3)
print(type(arr3))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


### dtype

In [82]:
int1 = np.array([1,2,3])
print(int1)
print(int1.dtype)

float1 = np.array([1,2,3],dtype=float)
print(float1)
print(float1.dtype)
# 64 bits = 8 bytes for np.float64

string1 = np.array(["a","b","c"])
print(string1)
print(string1.dtype)


string2 = np.array([1,2,3],dtype=str)
print(string2)
print(string2.dtype)

bool1 = np.array([1,2,3],dtype=bool)
print(bool1)
print(bool1.dtype)

complex1 = np.array([1,2,3],dtype=complex)
print(complex1)
print(complex1.dtype)


[1 2 3]
int64
[1. 2. 3.]
float64
['a' 'b' 'c']
<U1
['1' '2' '3']
<U1
[ True  True  True]
bool
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [83]:
arr_complex = np.array([1+2j, 3+4j], dtype=np.complex128)
print(arr_complex)

arr_bool = np.array([True, False, True], dtype=np.bool_)    ## np.bool_ = NumPy version of Python's bool.
print(arr_bool)
print(arr_bool.dtype)

# Masking = using a True/False array to filter or modify elements of a NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_mask = arr % 2 == 0
print(even_mask)

# print(arr[arr % 2 == 0])

[1.+2.j 3.+4.j]
[ True False  True]
bool
[False  True False  True False  True False  True False  True]


In [84]:
# The b you see before the strings means the string is a byte string (binary string) instead of a normal text (Unicode) string.
# Using S5 datatype
arr_exercise_str = np.array(['apple', 'banana', 'cherry'], dtype='S5')
print(arr_exercise_str)

# Use S6 to avoid truncation
arr_exercise_str = np.array(['apple', 'banana', 'cherry'], dtype='S6')
print(arr_exercise_str)

# Use str to auto detect the string length
arr_exercise_str = np.array(['apple', 'banana', 'cherry'], dtype='str')
print(arr_exercise_str)


[b'apple' b'banan' b'cherr']
[b'apple' b'banana' b'cherry']
['apple' 'banana' 'cherry']


In [85]:
int8 = np.array([1,2,3],dtype=np.int8)
print(int8)
print(int8.dtype)

int32 = np.array([1,2,3],dtype=np.int32)
print(int32)
print(int32.dtype)


[1 2 3]
int8
[1 2 3]
int32


### Attributes are properties of Numpy array

In [86]:
a1 = np.arange(10,dtype=np.int32)              ## vector
a2 = np.arange(12,dtype=float).reshape(3,4)    ## matrices
a3 = np.arange(8).reshape(2,2,2)               ## tensor
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [87]:
# ndim = no of dimensions

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [88]:
# shape = structure of array

print(a1.shape)   ## 10 elements in one dimension
print(a2.shape)
print(a3.shape)       ## (layers , rows , columns)

(10,)
(3, 4)
(2, 2, 2)


In [89]:
print(a1.shape[0])
# print(a1.shape[1])

print(a3.shape[0])
print(a3.shape[1])
print(a3.shape[2])
# print(a3.shape[3])    ## IndexError: tuple index out of range

10
2
2
2


In [90]:
# size = total elements

print(a1.size)
print(a2.size)
print(a3.size)         ## size = layers × rows × columns

10
12
8


In [91]:
# dtype = data type 

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [92]:
# itemsize = how many bytes each element in the array occupies in memory.

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [93]:
# nbytes = total memory
# In NumPy, nbytes tells you how much memory (in bytes) a NumPy array uses.
# It represents the total number of bytes consumed by the array elements.

print(a1.nbytes)      ## 10 elements × 4 bytes = 40 bytes
print(a2.nbytes)
print(a3.nbytes)   

40
96
64


### np.arrange(start,stop,step.dtype)
stop is not included 

#### np.arange() is a NumPy function used to create an array with evenly spaced  numbers within a range.
#### It is similar to Python’s range() function, but it returns a NumPy array instead of a range object.

In [94]:
arr = np.arange(5)   ##(0,5,1)
print(arr)

[0 1 2 3 4]


In [95]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [96]:
np.arange(0,2,0.5)      ## 0.5 is step size which generate decimal values

array([0. , 0.5, 1. , 1.5])

### reshape

In [97]:
a1 = np.arange(1,11).reshape(2,5)  ## 2rows 5 columns
print(a1)
a2 = np.arange(1,11).reshape(5,2) 
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [98]:
b = np.arange(1,13)
print(b,b.size)

b1 = np.arange(1,13).reshape(3,4)
print(b1)
b2 = np.arange(1,13).reshape(4,3)
print(b2)
b3 = np.arange(1,13).reshape(6,2)
print(b3)
b4 = np.arange(1,13).reshape(2,6)
print(b4)
# b4 = np.arange(1,13).reshape(5,5)    ## 5*5 = 25 but we have 12 elements only
print(b4)                            ## 5*5 must be equal to array.size 

[ 1  2  3  4  5  6  7  8  9 10 11 12] 12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [99]:
x = np.arange(1,11).reshape(-1)
print(x)
print(x.shape)

y = np.arange(1,11).reshape(5,-1)
print(y,y.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] (5, 2)


In [100]:
## using -1(automatic size)
# numpy can automatically calculate one dimension

arr = np.array([1,2,3,4,5,6])
print(arr,arr.shape,arr.size)
new_arr = arr.reshape(2,-1)
print(new_arr)
print(new_arr.shape)
print(new_arr.size)

new_arr2 = arr.reshape(-1,2)
print(new_arr2)
print(new_arr2.shape)
print(new_arr2.size)

[1 2 3 4 5 6] (6,) 6
[[1 2 3]
 [4 5 6]]
(2, 3)
6
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
6


In [101]:
arr2 = np.arange(24)
print(arr2,arr2.shape,arr2.size)

new = arr2.reshape(2,3,4)   ## 2matrices 3rows 4 columns
print(new,new.shape,new.size)

arr2 = np.arange(24)
print(arr2,arr2.shape,arr2.size)
new = arr2.reshape(2,3,-1)   ## 2matrices 3rows 4 columns
print(new,new.shape,new.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] (24,) 24
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4) 24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] (24,) 24
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4) 24


In [102]:
## reshape() changes shape not data

## id() tells where the object is stored in memory

arr = np.arange(6)
print(arr,arr.shape,arr.size)
print(id(arr))

new_arr = arr.reshape(2,3)
print(new_arr,new_arr.shape,new_arr.size)
print(id(new_arr))

# id of arr not equal to new_arr
# even though ids are different but both arrays use same data

# id(arr) and id(new_arr) are different because they are different Python objects.
# However, they share the same underlying memory buffer.

new_arr[0,0] = 100
print(arr)
print(new_arr)

print(id(arr))
print(id(new_arr))

# original array changed too 
# because both arrays are using the same memory data

[0 1 2 3 4 5] (6,) 6
1788734900720
[[0 1 2]
 [3 4 5]] (2, 3) 6
1788734544496
[100   1   2   3   4   5]
[[100   1   2]
 [  3   4   5]]
1788734900720
1788734544496


In [103]:
# view() creates a new array object but shares the same memory data.
# If you modify one array, the other changes too.

arr = np.array([1,2,3,4])
view_arr = arr.view()

print(arr,id(arr))
print(view_arr,id(view_arr))

view_arr[0] = 100

print(arr,id(arr))
print(view_arr,id(new_arr))

print(view_arr.base is arr)

[1 2 3 4] 1788734909360
[1 2 3 4] 1788734908784
[100   2   3   4] 1788734909360
[100   2   3   4] 1788734544496
True


In [104]:
# copy() creates a completely separate array with its own memory.
# Changing one does not affect the other.

arr = np.array([1,2,3,4])
copy_arr = arr.copy()

copy_arr[0] = 100

print(arr,id(arr))
print(copy_arr,id(copy_arr))

print(copy_arr.base is arr)

[1 2 3 4] 1788734545456
[100   2   3   4] 1788735395504
False


### np.ones   np.zeros

In [105]:
# np.zeros() creates an array where all elements are 0
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [107]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [108]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [109]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [110]:
# np.ones() creates an array where all elements are 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [111]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [112]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [113]:
# to initialize arrays

# in neural networks , nodes are connected and we call them weight
# eg(3,2) values are there ===>  then np.ones((3,2))

### np.random

In [114]:
np.random.rand(3)   ## numbers generated between 0 and 1(exclusive)

array([0.68194488, 0.21848119, 0.29977043])

In [115]:
np.random.randn(5)  ## generates numbers from a normal distribution

array([-1.20568646,  1.2728886 ,  0.55697253,  0.9149274 , -0.56518914])

In [116]:
np.random.random((3,4))  ## generates floating no between 0 and 1(exclusive)
# random ek class hai and uske andar ka method bhi random hai

array([[0.14315611, 0.72576235, 0.71587497, 0.24916573],
       [0.25413522, 0.83754974, 0.9170178 , 0.74930033],
       [0.58858597, 0.62693149, 0.9961636 , 0.05289228]])

In [117]:
# np.random.randint(low, high=None, size=None)
# high is exclusive
# generate random integers within a given range.

x = np.random.randint(10)
print(x)

x2 = np.random.randint(5, 20)
print(x2)

arr = np.random.randint(1, 10, size=5)
print(arr)

arr2 = np.random.randint(1, 10, size=(3,4))
print(arr2)

2
19
[6 4 2 3 7]
[[6 9 1 8]
 [8 9 9 4]
 [4 6 2 6]]


### np.linspace  = generate evenly spaced numbers between two values.
np.linspace(start,stop,num)

start and stop are included

dtype
None
Automatically inferred

In [118]:
np.linspace(-10,10,10)  

# equal distance pe sare points generate hoge 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [119]:
# linspace usually produces floating numbers
arr = np.linspace(1,10,10)
print(arr,arr.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float64


In [120]:
arr = np.linspace(0,10,5,endpoint=False)  ## 10 is excluded
print(arr)

[0. 2. 4. 6. 8.]


### np.identity

identity matrix is square matrix where:

diagonal elements = 1 ;
all other elements = 0

np.identity(n)  = creates n*n identity matrix

| Function         | Input         | Use         |
| ---------------- | ------------- | ----------- |
| `np.identity(n)` | Single number | Square only |
| `np.eye(r, c)`   | Rows, cols    | Any shape   |


In [121]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [122]:
# np.identity((3,3))  # np.identity() expects a single integer

In [123]:
# No, np.identity() is not used for 3D arrays. It only creates a 2D identity matrix.

In [124]:
# np.eye(rows,,cols)  = can create non square matrices

In [125]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [126]:
# Use identity() when you simply want:
        # n × n identity matrix


# Use eye() when you need:
        # rectangular matrices
        # shifted diagonals
        # more control

### astype()
astype() creates a new array, so the original array is NOT changed

astype() creates a copy, not a view.

In [127]:
arr = np.array([1,2,3,4])

new_arr = arr.astype(float)

print(arr,id(arr))
print(arr.dtype)

print(new_arr,id(new_arr))
print(new_arr.dtype)

new_arr[0] = 10.5

print(arr)         ## Proof That Original Array Doesn't Change
print(new_arr)

[1 2 3 4] 1788734546512
int64
[1. 2. 3. 4.] 1788734901584
float64
[1 2 3 4]
[10.5  2.   3.   4. ]


In [128]:
arr_int64 = np.array([1,2,3])
print(arr_int64,arr_int64.dtype)         ## 8 bytes per element

new_int16 = arr_int64.astype(np.int16)
print(new_int16,new_int16.dtype)         ## 2 bytes per element

# reduce memory usage
# improve efficiency
# match required datatype

[1 2 3] int64
[1 2 3] int16


In [129]:
a = np.array([1,2,3])
aa = a.astype(str)
print(aa)
print(a)

a2 = np.array([1.3,1.5,1.6])
f = a2.astype(int)
print(f)  ## truncates, it does not round

['1' '2' '3']
[1 2 3]
[1 1 1]


### Array operations

In [130]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [131]:
# In NumPy, a scalar operation on an array means applying a single value (scalar) to every element of the array automatically.

# scalar + array → operation applied to every element
# This happens automatically due to NumPy vectorization.

# arithmetic
print(a1+2)
print(a1**2)
print(a2+2)
print(a1/2)    ## float

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [132]:
# relational
print(a2>5)
print(a1>=5)
print(a2==15)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[[False False False  True]
 [False False False False]
 [False False False False]]


In [133]:
# vector operations = two numpy array pe operator apply kiya

print(a1+a2)  ## shape is same of both
print(a1-a2)
print(a1/a2)  ## float 

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


### Array functions
built-in functions used to create, manipulate, analyze, and transform arrays.

In [134]:
# mathematical functions

a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*100)
print(a1)

[[0.45044857 0.00183426 0.01850755]
 [0.71355278 0.2862603  0.31169236]
 [0.94548234 0.24356635 0.21641568]]
[[45.  0.  2.]
 [71. 29. 31.]
 [95. 24. 22.]]


In [135]:
print(np.max(a1))
print(np.argmax(a1))
print(np.sum(a1))
print(np.prod(a1))
print(np.mean(a1))
print(np.var(a1))
print(np.std(a1))
print(np.median(a1))

95.0
6
319.0
0.0
35.44444444444444
850.0246913580246
29.155182924448006
29.0


In [136]:
print(np.max(a1,axis=1))      ## 1 row 0 columns 
print(np.sum(a1,axis=0))

[45. 71. 95.]
[211.  53.  55.]


In [137]:
a3 = np.arange(8).reshape(2,2,2)               ## tensor
print(a3)
print(np.sum(a3))
print(np.sum(a3,axis=0))
print(np.sum(a3,axis=1))
print(np.sum(a3,axis=2))

# | Axis     | Meaning                     |
# | -------- | --------------------------- |
# | `axis=0` | Collapse **layers** (depth) |
# | `axis=1` | Collapse **rows**           |
# | `axis=2` | Collapse **columns**        |

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
28
[[ 4  6]
 [ 8 10]]
[[ 2  4]
 [10 12]]
[[ 1  5]
 [ 9 13]]


In [138]:
print(np.sin(a1))

[[ 0.85090352  0.          0.90929743]
 [ 0.95105465 -0.66363388 -0.40403765]
 [ 0.68326171 -0.90557836 -0.00885131]]


In [139]:
# dot product
# The dot product in NumPy is a mathematical operation used to multiply two arrays and sum the products.
# It is widely used in linear algebra, machine learning, and neural networks. 

# (m × n) · (n × p)
# Result shape: (m × p)

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [140]:
# 3,4    4,3
# number of columns in first array = number of rows in second array

print(np.dot(a2,a3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [141]:
a2@a3
# This is the modern Python operator for matrix multiplication.

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [142]:
a = np.array([[1,2],           ## 2,2
              [3,4]])

b = np.array([[5,6],           ## 2,2
              [7,8]])

print(np.dot(a,b))             ## 2,2

[[19 22]
 [43 50]]


In [143]:
# exp(x) = e^x
# e ≈ 2.718

print(np.exp(a2))

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


In [144]:
# A logarithm is the inverse of an exponent.
print(np.log(a3))     # np.log() calculates natural logarithm (base e).

print(np.log10(a3))   # np.log10() (Base 10 Log)

print(np.power(a2,2)) # a2^2

[[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422]]
[[1.07918125 1.11394335 1.14612804]
 [1.17609126 1.20411998 1.23044892]
 [1.25527251 1.2787536  1.30103   ]
 [1.32221929 1.34242268 1.36172784]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [145]:
# round floor ceil

m = np.random.random((2,3))*100
print(m)
print(np.round(m))
print(np.floor(m))
print(np.ceil(m))

[[84.69555801 63.13886857 71.88447058]
 [89.83025724 76.67209748 83.87446152]]
[[85. 63. 72.]
 [90. 77. 84.]]
[[84. 63. 71.]
 [89. 76. 83.]]
[[85. 64. 72.]
 [90. 77. 84.]]


Indexing: Rows are 0, Columns are 1

When you access elements, the order is:

array[row_index, column_index]

Axis Means "Direction of Operation"

axis tells NumPy which dimension to collapse during an operation.

For a 2D array:

axis=0 → vertical direction
axis=1 → horizontal direction

### Indexing    Slicing

In [146]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [147]:
print(a1[-1])

print(a2[1,2])
print(a2[2,3])

print(a3[1,0,1])
print(a3[0,0,0])

9
6
11
10
0


In [148]:
print(a2[0])
print(a2[-1])

print(a3[1])

[0 1 2 3]
[ 8  9 10 11]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [149]:
a1
print(a1[2:5])
print(a1[2:7:2])

[2 3 4]
[2 4 6]


In [150]:
a2 
# print(a2[0,:])
# print(a2[1:,1:3])
# print(a2[0::2,0::3])
# print(a2[0::2,1::2])
# print(a2[1,0::3])
# print(a2[0:2,1:4])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
a3
# print(a3[1])
# print(a3[0::2])
# print(a3[0,1,:])
# print(a3[1,:,1])
# print(a3[2,1:,1:])
print(a3[0::2,0,0::2])

[[ 0  2]
 [18 20]]


### Iteration

In [152]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [153]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [154]:
for i in a3:
    print(i)
   

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [155]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [156]:
for i in a3:
    for  j in i :
        for k in j:
            print(k)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
# hard way
# for i in range(arr.shape[0]):
#     for j in range(arr.shape[1]):
#         print((i, j), arr[i][j])

# easy way
# for index, value in np.ndenumerate(arr):
#     print(index, value) 
# 👉 Cleaner + works for ANY dimension (2D, 3D, etc.)            

| Feature     | `ndenumerate` 🟢 | `nditer` 🔵       |
| ----------- | ---------------- | ----------------- |
| Output      | (index, value)   | value only        |
| Speed       | Slower           | Faster ⚡          |
| Control     | Simple           | Advanced          |
| Use case    | Debugging        | Performance tasks |
| Multi-array | ❌ No             | ✅ Yes             |


In [169]:
# ndenumerate

import numpy as np

arr = np.array([[10, 20],
                [30, 40]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


In [170]:
arr = np.array([[[1,2],[3,4]]])

for idx, val in np.ndenumerate(arr):
    print(idx, val)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4


In [158]:
# np.ravel()
# NumPy function that converts a multi-dimensional array into a 1-D array (flattened array).
# It returns a contiguous flattened array
# Whenever possible, it returns a view of the original array (not a copy), which makes it faster and memory-efficient

print(a3)
print(np.ravel(a3))
print(a3.ravel())

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [159]:
# np.flatten()
# NumPy array method that converts a multi-dimensional array into a 1-D array.
# flatten() always returns a copy of the original array, not a view.

print(a3.flatten())
# print(np.flatten(a3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [160]:
# for x in a3.flatten():
#     print(x)

# for x in a3.ravel():
#     print(x)    

# for x in np.nditer(a3):
#     print(x)    

| Feature      | `ravel()`                    | `flatten()`              |
| ------------ | ---------------------------- | ------------------------ |
| Memory       | Returns **view if possible** | Always **returns copy**  |
| Speed        | Faster                       | Slightly slower          |
| Modification | May affect original array    | Does not affect original |


| Method  | Correct                              | Wrong              |
| ------- | ------------------------------------ | ------------------ |
| flatten | `array.flatten()`                    | `np.flatten()` ❌   |
| ravel   | `np.ravel(array)` or `array.ravel()` | `np.ravel` alone ❌ |


In [161]:
# sometimes in python 
# result dikh jaye then temporary operation , if result nahi dikhai de then permanent operation

In [162]:
# transpose
import numpy as np 

a = np.array([[1,2,3],
              [4,5,6]])
print(a,a.shape)

print(a.T,(a.T).shape)
print(np.transpose(a))

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 4]
 [2 5]
 [3 6]] (3, 2)
[[1 4]
 [2 5]
 [3 6]]


### Stacking

In [163]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4)
print(a5)

# multiple data sources ko jodna hai to do analysis

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [164]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [165]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [166]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [167]:
# vertical splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [168]:
#####

a = np.array([[10,20,30]])
print(a.shape)

b = np.array([[10],
              [20],
              [30]])

print(b.shape)

(1, 3)
(3, 1)
