
https://numpy.org/doc/stable/user/index.html

pip install -r requirements.txt



### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [1]:
import numpy as np

arr1 = np.array([1,2,3])
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# np.array() is a function
# np.array(object)    ## object is data structure containing numbers
# np.array(object,dtype=None,copy=True,ndmin=0)
# at least one argument is required to create a Numpy array
# ndmin = forces minimum number of dimensions

np.array([1,2,3])

array([1, 2, 3])

In [6]:
From_list = np.array([1,2,3])
From_tuple = np.array((1,2,3))
From_2darray = np.array([[1,2,3],[4,5,6]])

print(From_list)
print(From_tuple)
print(From_2darray)

[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [10]:
# numpy arrays reuire elements of same type 
arr = np.array([1,2,3.5])
print(arr)                   ## numpy converts everything to float automatically
print(arr.dtype)

[1.  2.  3.5]
float64


Fixed Size vs Dynamic Size

In [ ]:
# Python lists can grow or shrink anytime.

numbers = [1, 2, 3]
numbers.append(4)
print(numbers)
# Here the list grew dynamically.



[1, 2, 3, 4]


In [19]:
# NumPy arrays have a fixed size once created.

import numpy as np

arr = np.array([1,2,3])

print(arr)
print(id(arr))

arr = np.append(arr, 4)
print(arr)

print(id(arr))

# Behind the scenes, NumPy creates a new array and deletes the old one.

[1 2 3]
1569285913744
[1 2 3 4]
1569286263056


Store what kind of data

In [31]:
# Lists can store different types of data.


my_list = [1, "hello", 3.5, True]
print(my_list)

# Different types are allowed.


# NumPy arrays must have same data type.

import numpy as np

arr = np.array([1,2,3,4])
print(arr)

# All elements are integers.

# If you mix types:

arr = np.array([1,2,3.5])
print(arr)

# NumPy converts all values to float automatically.
# numpy chooses more general type
# float represent integer but integer cannot represent decimals

[1, 'hello', 3.5, True]
[1 2 3 4]
[1.  2.  3.5]


NumPy is designed for fast mathematical calculations.

In [22]:
# list requires loop
list1 = [1,2,3]
list2 = [4,5,6]

result = []
for i in range(len(list1)):
    result.append(list1[i] + list2[i])

print(result)


# No loop needed
# Less code
# Faster computation
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

[5, 7, 9]
[5 7 9]


Many scientific libraries in Python use NumPy internally.

Examples:

Pandas (data analysis)

Matplotlib (plotting graphs)

SciPy (scientific computing)

Scikit-learn (machine learning)

Even if you give them Python lists, they usually convert them into NumPy arrays first.

In [26]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)
# list concatenate not add

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
# element wise addition happens

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [29]:
m = [1,2,3]
print(a*2)
# it repeats list

n = np.array([1,2,3])
print(n*2)
# each element multiplied

[1, 2, 3, 1, 2, 3]
[2 4 6]
