In [190]:
import numpy as np

In [191]:
scalar = np.array(1)                ## scalar
print(scalar)
print(type(scalar))

# print(np.array(1,2))

# 0-dimensional NumPy array, also called a scalar array.
# A scalar means a single number (not a list or matrix).

1
<class 'numpy.ndarray'>


In [192]:
arr1 = np.array([1,2,3,4,5])             ## vector
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [193]:
arr2 = np.array([[1,2,3],[4,5,6]])             ## matrices
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [194]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])       ## tensor
print(arr3)
print(type(arr3))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


### dtype

In [195]:
int1 = np.array([1,2,3])
print(int1)
print(int1.dtype)

float1 = np.array([1,2,3],dtype=float)
print(float1)
print(float1.dtype)

string1 = np.array(["a","b","c"])
print(string1)
print(string1.dtype)

bool1 = np.array([1,2,3],dtype=bool)
print(bool1)
print(bool1.dtype)

complex1 = np.array([1,2,3],dtype=complex)
print(complex1)
print(complex1.dtype)


[1 2 3]
int64
[1. 2. 3.]
float64
['a' 'b' 'c']
<U1
[ True  True  True]
bool
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [196]:
int8 = np.array([1,2,3],dtype=np.int8)
print(int8)
print(int8.dtype)

int32 = np.array([1,2,3],dtype=np.int32)
print(int32)
print(int32.dtype)


[1 2 3]
int8
[1 2 3]
int32


### Attributes are properties of Numpy array

In [197]:
a1 = np.arange(10,dtype=np.int32)              ## vector
a2 = np.arange(12,dtype=float).reshape(3,4)    ## matrices
a3 = np.arange(8).reshape(2,2,2)               ## tensor
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [198]:
# ndim = no of dimensions

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
# shape = structure of array

print(a1.shape)   ## 10 elements in one dimension
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [200]:
# size = total elements

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [201]:
# itemsize = memory per element

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [202]:
# nbytes = total memory

print(a1.nbytes)
print(a2.nbytes)
print(a3.nbytes)

40
96
64


In [203]:
# dtype = data type 

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### np.arrange(start,stop,step.dtype)
stop is not included 

#### np.arange() is a NumPy function used to create an array with evenly spaced  numbers within a range.
#### It is similar to Python’s range() function, but it returns a NumPy array instead of a range object.

In [204]:
arr = np.arange(5)   ##(0,5,1)
print(arr)

[0 1 2 3 4]


In [205]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [206]:
np.arange(0,2,0.5)      ## 0.5 is step size which generate decimal values

array([0. , 0.5, 1. , 1.5])

### reshape

In [207]:
a1 = np.arange(1,11).reshape(2,5)  ## 2rows 5 columns
print(a1)
a2 = np.arange(1,11).reshape(5,2) 
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [208]:
b = np.arange(1,13)
print(b,b.size)

b1 = np.arange(1,13).reshape(3,4)
print(b1)
b2 = np.arange(1,13).reshape(4,3)
print(b2)
b3 = np.arange(1,13).reshape(6,2)
print(b3)
b4 = np.arange(1,13).reshape(2,6)
print(b4)
b4 = np.arange(1,13).reshape(5,5)    ## 5*5 = 25 but we have 12 elements only
print(b4)                            ## 5*5 must be equal to array.size 

[ 1  2  3  4  5  6  7  8  9 10 11 12] 12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


ValueError: cannot reshape array of size 12 into shape (5,5)

In [ ]:
## using -1(automatic size)
# numpy can automatically calculate one dimension

arr = np.array([1,2,3,4,5,6])
print(arr,arr.shape,arr.size)
new_arr = arr.reshape(2,-1)
print(new_arr)
print(new_arr.shape)
print(new_arr.size)

[1 2 3 4 5 6] (6,) 6
[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [ ]:
arr2 = np.arange(24)
print(arr2,arr2.shape,arr2.size)
new = arr2.reshape(2,3,4)   ## 2matrices 3rows 4 columns
print(new,new.shape,new.size)

arr2 = np.arange(24)
print(arr2,arr2.shape,arr2.size)
new = arr2.reshape(2,3,-1)   ## 2matrices 3rows 4 columns
print(new,new.shape,new.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] (24,) 24
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4) 24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] (24,) 24
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4) 24


In [ ]:
## reshape() changes shape not data

## id() tells where the object is stored in memory

arr = np.arange(6)
print(arr,arr.shape,arr.size)
print(id(arr))

new_arr = arr.reshape(2,3)
print(new_arr,new_arr.shape,new_arr.size)
print(id(new_arr))

# id of arr not equal to new_arr
# even though ids are different but both arrays use same data

new_arr[0,0] = 100
print(arr)
print(new_arr)

# original array changed too 
# because both arrays are using the same memory data

[0 1 2 3 4 5] (6,) 6
2347905679056
[[0 1 2]
 [3 4 5]] (2, 3) 6
2347904371088
[100   1   2   3   4   5]
[[100   1   2]
 [  3   4   5]]


### np.ones   np.zeros

In [ ]:
# np.zeros() creates an array where all elements are 0
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
# np.ones() creates an array where all elements are 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
# to initialize arrays

# in neural networks , nodes are connected and we call them weight
# eg(3,2) values are there ===>  then np.ones((3,2))

### np.random

In [ ]:
np.random.rand(3)   ## numbers generated between 0 and 1(exclusive)

array([0.31771929, 0.59661668, 0.46893597])

In [ ]:
np.random.randn(5)  ## generates numbers from a normal distribution

array([ 1.22309615,  0.38301992,  0.55055291, -0.97480661,  0.52375759])

In [ ]:
np.random.random((3,4))  ## generates floating no between 0 and 1(exclusive)

array([[0.23379859, 0.32230334, 0.58434016, 0.50826051],
       [0.96424079, 0.71249838, 0.80121392, 0.94426743],
       [0.88752511, 0.79940923, 0.50671619, 0.43083416]])

### np.linspace
np.linspace(start,stop,num)

start and stop are included

In [ ]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# linspace usually produces floating numbers
arr = np.linspace(1,10,10)
print(arr,arr.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float64


In [ ]:
arr = np.linspace(0,10,5,endpoint=False)  ## 10 is excluded
print(arr)

[0. 2. 4. 6. 8.]


### np.identity

identity matrix is square matrix where:

diagonal elements = 1 ;
all other elements = 0

np.identity(n)  = creates n*n identity matrix

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# np.eye(rows,,cols)  = can create non square matrices

In [ ]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])