| Function  | Meaning                          |
| --------- | -------------------------------- |
| `len(a)`  | Length of first axis (rows)      |
| `a.size`  | Total elements in the array      |
| `a.shape` | Full dimensions (e.g., `(3, 4)`) |


In [79]:
import numpy as np

a = np.arange(10)

print(len(a))   # 10
print(a.size)   # 10

# Both return total elements because there's only one dimension.

10
10


In [80]:
a = np.arange(12).reshape(3, 4)

print(len(a))   # 3
print(a.size)   # 12

# For multi-dimensional arrays:
            # len(a) → number of rows (first dimension)
            # a.size → total number of elements (rows × columns)

3
12


### Numpy array vs Python lists

In [81]:
a = [1,2,3]
b = [4,5,6]
print(a+b)

# it combines lists, not mathematical addition

# to add numbers element-wise, you must use a loop or comprehension

[1, 2, 3, 4, 5, 6]


In [82]:

a = [i for i in range(10000000)]     ## list comprehension
a = range(10000000)                  ## use a generator 
print(len(a))

b = [i for i in range(10000000,20000000)]
print(len(b))

10000000
10000000


In [83]:
# time

a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time 
start = time.time()

for i in range(len(a)):
    c.append(a[i]+b[i])

end = time.time() - start    
print(end)

print(len(c))


3.2764594554901123
10000000


In [84]:
import numpy as np

a = np.arange(10000000)

b = np.arange(10000000,20000000)

start = time.time()
c = a+b
end = time.time() - start
print(end)

print(len(c))

0.10270476341247559
10000000


In [85]:
3.5155029296875/0.10633707046508789   ## 33 times numpy is faster than list

# numpy uses c type  array  which is static  array and is not a referential array 
# numpy store item in memory directly and na ki uska address

# python list is dynamic and referential array (store item's address not its value directly)

33.059994170534296

In [86]:
## memory

import sys

a = [i for i in range(10000000)]

print(sys.getsizeof(a))

# sys.getsizeof(a) does NOT measure the total memory of the list contents — it only measures the list object itself.


89095160


In [87]:
a = np.arange(10000000)
print(sys.getsizeof(a))

80000112


In [88]:
a1 = np.arange(10000000,dtype=np.int32)
print(sys.getsizeof(a1))

40000112


In [89]:
a1 = np.arange(10000000,dtype=np.int16)
print(sys.getsizeof(a1))

20000112


In [90]:
a1 = np.arange(10000000,dtype=np.int8)  
print(sys.getsizeof(a1))

### que : int8 mei 1crore kese store hua?

10000112


In [91]:
# int8 can only hold numbers from:  -128 to 127
# That’s just 256 total values
# 👉 So it’s like a box with only 256 slots

| Situation                   | More Convenient |
| --------------------------- | --------------- |
| Quick scripting             | 🟢 List         |
| Mixed data                  | 🟢 List         |
| Heavy calculations          | 🔵 NumPy        |
| Large datasets              | 🔵 NumPy        |
| Learning programming basics | 🟢 List         |
| Data science / ML           | 🔵 NumPy        |


In [92]:
# convenience

a = [1, 2, 3]
b = [x * 2 for x in a]
print(b)

a = np.array([1, 2, 3])
b = a * 2
print(b)

[2, 4, 6]
[2 4 6]


### Advanced Indexing

In [93]:
# Normal indexing and slicing


In [94]:
# Fancy indexing

In [95]:
# Boolean indexing: means filtering an array using True/False values.

a = np.random.randint(1,100,24)
print(a)
a = np.random.randint(1,100,24).reshape(6,4)
print(a)

[22 15 29  5 45 23 68 57 62 21 79 11 63 13 62 13 65  8 28 12 99  4 29 95]
[[96 90  6 18]
 [40 20 37 83]
 [67 49 26 28]
 [75 94  6 43]
 [26 82 86 78]
 [10 55 51 17]]


In [96]:
# find numbers greatern than 50

print(a[a>50])
a > 50

[96 90 83 67 75 94 82 86 78 55 51]


array([[ True,  True, False, False],
       [False, False, False,  True],
       [ True, False, False, False],
       [ True,  True, False, False],
       [False,  True,  True,  True],
       [False,  True,  True, False]])

In [97]:
# find out even numbers

print(a[a%2==0])

a % 2 == 0

[96 90  6 18 40 20 26 28 94  6 26 82 86 78 10]


array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [98]:
# find all no greater than 50 and are even

print(a[(a>50) & (a%2==0)])

(a>50) & (a%2==0)

# used bitwise &


[96 90 94 82 86 78]


array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True],
       [False, False, False, False]])

In [99]:
# find all numbers not divisible by 7

print(a[a % 7 == 0])
a % 7 == 0

[49 28]


array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [100]:
# Boolean Masking 
a = np.array([1, 2, 3, 4])

a[a > 2]   # [3, 4]

# 👉 Used for filtering datasets (like SQL WHERE)

array([3, 4])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>

---


- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [ ]:
# Vectorization uses broadcasting to avoid loops

### Working with mathematical formulas